./csv2invoice data/examples/Example.csv -o data/examples/Example_.xml -e utf-16 -v
./csv2invoice data/examples/Example1.csv -o data/examples/Example1_.xml -e utf-16 -v
./csv2invoice data/examples/Example2-TaxAcctCur.csv -o data/examples/Example2-TaxAcctCur_.xml -e utf-16 -v
./csv2invoice data/examples/Example3-SumInv1.csv -o data/examples/Example3-SumInv1_.xml -e utf-16 -v
./csv2invoice data/examples/Example4-SumInv2.csv -o data/examples/Example4-SumInv2_.xml -e utf-16 -v
./csv2invoice data/examples/Example5-AllowanceCharge.csv -o data/examples/Example5-AllowanceCharge_.xml -e utf-16 -v
./csv2invoice data/examples/Example6-CorrInv.csv -o data/examples/Example6-CorrInv_.xml -e utf-16 -v
./csv2invoice data/examples/Example7-Return.Quan.csv -o data/examples/Example7-Return.Quan_.xml -e utf-16 -v
./csv2invoice data/examples/Example8-Return.ItPr.csv -o data/examples/Example8-Return.ItPr_.xml -e utf-16 -v