./csv2xbrl xBRL/csv/Example.csv -o xBRL/csv/Example_xbrl.xml -e utf-16 -v
./csv2xbrl xBRL/csv/Example1.csv -o xBRL/csv/Example1_xbrl.xml -e utf-16 -v
./csv2xbrl xBRL/csv/Example2-TaxAcctCur.csv -o xBRL/csv/Example2-TaxAcctCur_xbrl.xml -e utf-16 -v
./csv2xbrl xBRL/csv/Example3-SumInv1.csv -o xBRL/csv/Example3-SumInv1_xbrl.xml -e utf-16 -v
./csv2xbrl xBRL/csv/Example4-SumInv2.csv -o xBRL/csv/Example4-SumInv2_xbrl.xml -e utf-16 -v
./csv2xbrl xBRL/csv/Example5-AllowanceCharge.csv -o xBRL/csv/Example5-AllowanceCharge_xbrl.xml -e utf-16 -v
./csv2xbrl xBRL/csv/Example6-CorrInv.csv -o xBRL/csv/Example6-CorrInv_xbrl.xml -e utf-16 -v
./csv2xbrl xBRL/csv/Example7-Return.Quan.csv -o xBRL/csv/Example7-Return.Quan_xbrl.xml -e utf-16 -v
./csv2xbrl xBRL/csv/Example8-Return.ItPr.csv -o xBRL/csv/Example8-Return.ItPr_xbrl.xml -e utf-16 -v